# code: language=ansible
---
# Docker image versions for Home Assistant role
homeassistant_image: "homeassistant/home-assistant"
homeassistant_version: "stable"
mosquitto_image: "eclipse-mosquitto"
mosquitto_version: "2.0"
myelectricaldata_image: "m4dm4rtig4n/myelectricaldata"
myelectricaldata_version: "latest"
frigate_image: "ghcr.io/blakeblackshear/frigate"
frigate_version: "stable"
esphome_image: "esphome/esphome"
esphome_version: "stable"
zigbee2mqtt_image: "koenkk/zigbee2mqtt"
zigbee2mqtt_version: "2"
