# code: language=ansible
---
# Docker image versions for Traefik role
traefik_image: "traefik"
traefik_version: "v3.6"
unbound_image: "alpinelinux/unbound"
unbound_version: "latest"
unbound_exporter_git_repo: "https://github.com/letsencrypt/unbound_exporter.git"
unbound_exporter_git_version: "v0.5.0"
unbound_exporter_image: "local/unbound-exporter"
unbound_exporter_version: "v0.5.0"
unbound_offline_fallback_enabled: true
unbound_compose_project_name: "traefik"
alpine_image: "alpine"
alpine_version: "3.23"
