# code: language=ansible
---
- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: true

- name: Restart fail2ban
  become: true
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true
...
