#! /bin/bash

set -e

service=$1
bash=$2
options=$3

serviceID=$(sudo docker service ps -f name=$service -f desired-state=running $service -q --no-trunc |head -n1)
node=$(sudo docker service ps -f name=$service -f desired-state=running $service --format="{{.Node}}"| head -n1 )
if [ $(hostname) = $node ]; then
echo "docker exec $options $service"".1.""$serviceID $bash"
sudo docker exec $options $service".1."$serviceID $bash 
else
echo "docker -H $node exec $options $service"".1.""$serviceID $bash"
sudo docker -H $node exec $options $service".1."$serviceID $bash
fi