# yaml-langage-server: $schema=https://frigate.{{ app_domain_name }}/api/config/schema.json
auth:
  enabled: False

tls:
  enabled: False

proxy:
  # See https://github.com/blakeblackshear/frigate/discussions/19950
  auth_secret: "{{ frigate_proxy_auth_secret }}"
  header_map:
    user: x-authentik-username
    role: x-frigate-role

mqtt:
  user: "{{ mqtt_user }}"
  password: "{{ mqtt_password }}"
  host: mqtt
  port: 1883

{% if gpu != "none" % }
ffmpeg:
  hwaccel_args: {% if gpu == "intel" %}preset-intel-qsv-h265{% elif gpu == "nvidia" %}preset-nvidia{% endif %}
{% endif %}

detectors:
  {% if gpu == "intel" %}
  ov_0:
    type: openvino
    device: GPU
  {% else %}
  onnx_0:
    type: onnx
  {% endif %}

model:
  path: /config/model_cache/{{ frigate_model_filename }}
  model_type: yolo-generic
  width: {{ frigate_image_size }}
  height: {{ frigate_image_size }}
  input_tensor: nchw
  input_pixel_format: rgb
  input_dtype: float
  {% if gpu == "intel" %}
  labelmap_path: /labelmap/coco-80.txt
  {% endif %}