# yaml-langage-server: $schema=https://frigate.{{ app_domain_name }}/api/config/schema.json
auth:
  enabled: False

tls:
  enabled: False

proxy:
  # See https://github.com/blakeblackshear/frigate/discussions/19950
  auth_secret: "{{ frigate_proxy_auth_secret }}"
  header_map:
    user: x-authentik-username
    role: x-frigate-role

mqtt:
  user: "{{ mqtt_user }}"
  password: "{{ mqtt_password }}"
  host: mqtt
  port: 1883

{% if gpu == "nvidia" %}
# Globally set nvidia hwaccel
ffmpeg:
  hwaccel_args: preset-nvidia  # Hardware acceleration for both H.264 and H.265 streams

detectors:
  onnx_0:
    type: onnx
model:
  path: /config/model_cache/{{ frigate_model_filename }}
  model_type: yolo-generic
  width: {{ frigate_image_size }}
  height: {{ frigate_image_size }}
  input_tensor: nchw
  input_pixel_format: rgb
  input_dtype: float
{% endif %}