---
# Docker Configuration

# Combined server (Management + Signal + Relay + STUN)
netbird_combined_image: "netbirdio/netbird"
netbird_combined_version: "latest"
netbird_dashboard_image: "netbirdio/dashboard"
netbird_dashboard_version: "latest"

# Environment
netbird_environment:
  NETBIRD_JWT_ISSUER: "{{ netbird_oidc_issuer }}"
  NETBIRD_JWT_AUDIENCE: "{{ netbird_oidc_audience }}"

netbird_stun_port: 3478