---
# Docker Configuration

# Combined server (Management + Signal + Relay + STUN)
netbird_combined_image: "netbirdio/netbird-server"
netbird_combined_version: "latest"
netbird_dashboard_image: "netbirdio/dashboard"
netbird_dashboard_version: "latest"

netbird_stun_port: 3479 # To avoid same port as Nextcloud Turn Server
  